using Domain.Constants;
using Domain.Events;
using Microsoft.Extensions.AI;

namespace Application.Agent;

/// <summary>
/// Represents an agent that has finished it's work.
/// </summary>
/// <param name="Duration">The total duration of the assistant's work.</param>
/// <param name="History">The history of chat messages generated by the agent during a run.</param>
public sealed record AgentFinishedEvent(TimeSpan Duration, List<ChatMessage> History) : AgentEvent(Type: EventConstants.AgentFinished);