using System.Text.Json.Serialization;
using Microsoft.Extensions.AI;
using Domain.Constants;
using Domain.Events;

namespace Application.Agent;

/// <summary>
/// Represents an agent that has finished it's work.
/// </summary>
/// <param name="Duration">The total duration of the assistant's work.</param>
/// <param name="History">The history of chat messages generated by the agent during a run.</param>
public sealed record AgentFinishedEvent(TimeSpan Duration, List<ChatMessage> History) : AgentEvent(Type: EventConstants.AgentFinished)
{
    /// <summary>
    /// The history of chat messages generated by the agent during a run.
    /// <para>
    /// Ignored by JSON serialization- it's only for the server.
    /// </para>
    /// </summary>
    [JsonIgnore]
    public readonly List<ChatMessage> History = History;
}